#ifndef TOKEN_DEFINITIONS
#define TOKEN_DEFINITIONS

typedef enum tokens {
	TOKEN_ID,
	TOKEN_ASSIGNMENT,
	TOKEN_END_EXP,
	TOKEN_INTEGER_LITERAL,
	TOKEN_FLOAT_LITERAL,
	TOKEN_STRING_LITERAL,
	TOKEN_CHAR_LITERAL,
	TOKEN_COMENT,
	TOKEN8,
	TOKEN9,
	TOKEN10,
	TOKEN11,
	TOKEN12,
	TOKEN13,
}TokenType;

#endif // TOKEN_DEFINITIONS
