#ifndef TOKEN_DEFINITIONS
#define TOKEN_DEFINITIONS

typedef enum tokens {
    TOKEN_PREPROCESSOR_COMAND,
    TOKEN_KEYWORD,
    TOKEN_DATA_TYPE,
    TOKEN_ASSIGNMENT,
    TOKEN_ARITHMETIC_OPERATOR,
    TOKEN_RELATIONAL_OPERATOR,
    TOKEN_END_EXP,
    TOKEN_BLOCK_BEGIN,
    TOKEN_BLOCK_END,
    TOKEN_EXPRESSION_BEGIN,
    TOKEN_EXPRESSION_END,
    TOKEN_INTEGER_LITERAL,
    TOKEN_FLOAT_LITERAL,
    TOKEN_STRING_LITERAL,
    TOKEN_CHAR_LITERAL,
    TOKEN_ID
}TokenType;

#endif // TOKEN_DEFINITIONS
