#ifndef TOKEN_DEFINITIONS
#define TOKEN_DEFINITIONS

typedef enum tokens {
    TOKEN_KEYWORD,
    TOKEN_DATA_TYPE,
    TOKEN_ASSIGNMENT,
    TOKEN_END_EXP,
    TOKEN_INTEGER_LITERAL,
    TOKEN_FLOAT_LITERAL,
    TOKEN_STRING_LITERAL,
    TOKEN_CHAR_LITERAL,
    TOKEN_COMENT,
    TOKEN_ARITMETIC_OPERATOR,
    TOKEN_RELATIONAL_OPERATOR,
    BLOCK_BEGIN,
    BLOCK_END,
    EXPRESSION_BEGIN,
    EXPRESSION_END,
    TOKEN_ID,
}TokenType;

#endif // TOKEN_DEFINITIONS
